version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ro_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT_EXTERNAL:-5433}:5432"
    volumes:
      - ro_postgres_data:/var/lib/postgresql/data
    networks:
      - ro_network

volumes:
  ro_postgres_data:

networks:
  ro_network:
