services:
  postgres:
    image: postgres:latest
    container_name: ro_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rodevtest
    ports:
      - "5433:5432"
    volumes:
      - ro_postgres_data:/var/lib/postgresql/data
    networks:
      - ro_network

volumes:
  ro_postgres_data:

networks:
  ro_network:
