services:
  postgres:
    image: postgres:latest
    container_name: ro_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rodevtest
    ports:
      - "5433:5432"
    volumes:
      - ro_postgres_data:/var/lib/postgresql/data
    networks:
      - ro_network

  web:
    build:
      context: .
      dockerfile: RO.DevTest.WebApi/Dockerfile
    container_name: ro_api
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - ro_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Host=postgres;Port=5432;Database=rodevtest;Username=postgres;Password=1234;

volumes:
  ro_postgres_data:

networks:
  ro_network:
