
services:
  postgres:
    image: postgres:latest
    container_name: ro_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rodevtest
    ports:
      - "5433:5432"               # host:container
    volumes:
      - ro_postgres_data:/var/lib/postgresql/data
    networks:
      - ro_network               # rede compartilhada

  webapi:
    image: rodevtestwebapi:dev   # sua imagem pronta
    container_name: ro_webapi
    depends_on:
      - postgres
    environment:
      # Certifique-se de usar o mesmo nome usado no GetConnectionString(...)
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=rodevtest;Username=postgres;Password=1234;
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - ro_network               # mesma rede do postgres

volumes:
  ro_postgres_data:
    driver: local

networks:
  ro_network:
    name: ro_network            # força o nome limpo
    driver: bridge
